version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entering build phase....
      - npm install
      - npm run webpack
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - favicon.ico
    - AlexanderMerkulov.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
