version: 0.1

phase:
  build:
    commands:
      - echo Nothing to do yet
      - npm install
      - npm run webpack --mode production
artifacts:
  files:
    - index.html
    - favicon.ico
    - AlexanderMerkulov.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
